# Generated by Django 3.2 on 2022-01-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20210830_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteduser',
            name='candidate_branch',
            field=models.CharField(default='cse', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitteduser',
            name='candidate_studying_year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
